- litr-demo/build.gradle
- litr-demo/src/main/java/com/linkedin/android/litr/demo/MainActivity.java
- litr-filters/build.gradle
- litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/AnimatedGifOverlayFilter.java
- litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/AnimationFrameProvider.java
- litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BaseOverlayGlFilter.java
- litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BitmapOverlayFilter.java
- litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/FrameSequenceAnimationOverlayFilter.java
Implementation of new filter, which overlays animated GIFs on top of a video.
- Static bitmap and animated GIF filters share a lot of common logic, which is now abstracted into base class. Difference between classes is now how they load a texture from file and which texture ID is rendered onto video frame at a given presentation time. 
- Using Glide to load animated GIF
- Animated GIF frames are loaded into a circular buffer, along with their delays (duration of each frame)
> Animated GIF overlay filter

- README.md
- litr-demo/src/main/java/com/linkedin/android/litr/demo/MainActivity.java
- litr-filters/build.gradle
- litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BaseOverlayGlFilter.java
- litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BitmapOverlayFilter.java
- litr/build.gradle
- litr/src/main/java/com/linkedin/android/litr/filter/GlFilter.java
- litr/src/main/java/com/linkedin/android/litr/render/GlVideoRenderer.java
- litr/src/main/java/com/linkedin/android/litr/render/VideoRenderer.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoder.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoderShould.java
Reworking some OpenGL rendering logic to fix bitmap overlays becoming distorted when rotated:
- Introducing projection matrix in GlVideoRenderer. Using projection matrix is essential for correct scaling in non-square canvas. 
- Passing in video frame aspect ratio to renderer. Breaking change in interface, so bumping a minor version. 
- Renderer now sets up projection in addition to view matrix and passes it to filters. 
- Bitmap overlay filters extract video frame aspect ratio and orientation to apply correct transformations to bitmaps.
> Fixing overlay geometry.

- litr-demo/src/main/java/com/linkedin/android/litr/demo/BaseTransformationFragment.java
- litr-demo/src/main/java/com/linkedin/android/litr/utils/TransformationUtil.java
- litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java
- litr/src/main/java/com/linkedin/android/litr/io/MediaExtractorMediaSource.java
- litr/src/main/java/com/linkedin/android/litr/io/MediaSource.java
- litr/src/main/java/com/linkedin/android/litr/render/GlVideoRenderer.java
- litr/src/main/java/com/linkedin/android/litr/render/VideoRenderer.java
- litr/src/main/java/com/linkedin/android/litr/utils/TranscoderUtils.java
- litr/src/test/java/com/linkedin/android/litr/utils/TranscoderUtilsShould.java
In current implementation LiTr doesn't apply overlays if target video format is null. Which may be inconvenient for clients who want to modify video frames without changing resolution or bitrate. 
Now LiTr will make sure overlays are always applied. The catch is that on many devices bitrate is not provided for video tracks, for which we implement a utility method to estimate it.
> Applying overlays when target video format is null

- litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java
- litr/src/main/java/com/linkedin/android/litr/TrackTransform.java
- litr/src/main/java/com/linkedin/android/litr/render/GlVideoRenderer.java
- litr/src/main/java/com/linkedin/android/litr/render/Renderer.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/TrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/TrackTranscoderFactory.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoder.java
- litr/src/test/java/com/linkedin/android/litr/TransformationJobShould.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoderShould.java
In anticipation of software renderers (both for video and audio) we need to generalize renderer interface and change init method to accept source and target MediaFormat.
> Making VideoRenderer interface more general purpose Renderer interface.

- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java
- litr/src/main/java/com/linkedin/android/litr/codec/MediaCodecEncoder.java
When running in Surface mode, on many devices MediaCodec encoder requires color format to be set in target format. COLOR_FormatSurface is most compatible for surface mode.
> Default encoder to use COLOR_FormatSurface

- litr/src/main/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/PassthroughTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/TrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/utils/TranscoderUtils.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoderShould.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/PassthroughTranscoderShould.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoderShould.java
Some tracks (for example, metadata track) do not have duration. In our code we assume that they do. No longer making that assumption.
We are also moving duration extraction into base class.
> Handling tracks with no duration

- litr/src/main/java/com/linkedin/android/litr/MarshallingTransformationListener.java
Provided looper was not used to initialize the MarshallingHandler which would use the `Looper.myLooper()` of whatever thread the transform job was submitted on.
I'm not sure how to test this nor if it makes sense to. But happy to follow your guidance if you have any idea :)
Best and thanks for this library 👍
> Fixing MarshallingHandler not using provided looper

- litr/src/main/java/com/linkedin/android/litr/filter/GlFrameRenderFilter.java
- litr/src/main/java/com/linkedin/android/litr/filter/video/gl/ScaleToFitGlFrameRenderFilter.java
- litr/src/main/java/com/linkedin/android/litr/render/GlVideoRenderer.java
- litr/src/main/java/com/linkedin/android/litr/render/VideoRenderInputSurface.java
GlVideoRenderer performed both management of input/output surfaces and rendering from input onto output surface. Rendering was very simple "scale to fit" between the two surfaces. 
Now splitting that logic into two: 
- renderer manages surfaces
- video frame rendering from input onto output surface is implemented as a filter. We introduce new type of filters to do this, which is given access to input video surface texture id and matrix.
- default frame rendering filter implementation is current "scale to fit" mapping.
This refactor will allow us to add more sophisticated frame rendering filters implementing transformations like cropping, rotation, etc.
> Support for custom video frame renderers

- litr-demo/src/main/java/com/linkedin/android/litr/demo/BaseTransformationFragment.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoCase.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/FreeTransformVideoGlFragment.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TargetMedia.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TargetVideoConfiguration.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java
- litr-demo/src/main/res/layout/fragment_video_overlay_gl.xml
- litr-demo/src/main/res/layout/section_target_video_configuration.xml
- litr-demo/src/main/res/values/strings.xml
- litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/FreeTransformFrameRenderFilter.java
- litr/src/main/java/com/linkedin/android/litr/render/GlVideoRenderer.java
A frame render filter, which supports geometric transformation of a source video frame when rendering it onto a target video frame:
- since source and target video orientations no longer match, client must pass in target video orientation when using this renderer, if orientations don't match
- scaling/rotating/positioning logic works pretty much the same way as for bitmap overlays. Except now we have to know orientation of a source video to display it correctly. 
- new demo fragment allows experimenting with different setups: target video orientation, transform parameters, etc.
> Filter for free transform video frame rendering

- litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BaseOverlayGlFilter.java
We were flipping overlay bitmaps in transformation matrix, to match video orientation. Now we do similar to how it is done in video frames, using texture matrix.
> Flip overlay bitmap using texture matrix, similar to video frame

- litr-filters/src/main/java/com/linkedin/android/litr/filter/util/GlFilterUtil.java
- litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BaseOverlayGlFilter.java
- litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/FreeTransformFrameRenderFilter.java
Both bitmap and video frame transformations use the same logic for calculating MVP matrix based on target video frame VP matrix and overlay size/position/rotation. We are moving that logic into a separate util method.
> Refactor filter MVP matrix calculation into util method

- litr/src/main/java/com/linkedin/android/litr/render/PassthroughSoftwareRenderer.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/PassthroughTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/TrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/TrackTranscoderFactory.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoder.java
- litr/src/test/java/com/linkedin/android/litr/render/PassthroughSoftwareRendererShould.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoderShould.java
Factoring out "rendering" logic in AudioTrackTranscoder into a separate PassthroughSoftwareRenderer, which simply copies decoder output buffer into encoder input buffer. Renderer is "synchronous" - when it is asked to render, it waits for encoder to dequeue an input buffer, then fills it with input frame data and releases back to encoder. If wait times out, buffer is dropped, similar to video GL renderer.
> Implementation of PassthroughSoftwareRenderer

- litr/src/main/java/com/linkedin/android/litr/render/GlVideoRenderer.java
For one of my project I had to apply a black and white filter to the video. To achieve this I had to extend the GlVideoRenderer to modify the fragment shader. Would be nice to be able to directly override the default fragment shader to apply some transformations upon GlVideoRenderer instantiation.
> allow to override fragment shader

- litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/SolidBackgroundColorFilter.java
Color.red/green/blue() returns int from 0 to 255, while we expect a float from 0.0f to 1.0f
> Fix SolidBackgroundColorFilter ColorInt constructor

- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java
- litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java
- litr/src/main/java/com/linkedin/android/litr/utils/CodecUtils.java
Introducing a new utility, which allows picking highest supported codec profile. Optionally, clients can specify a "desired" profile, in which case utility will use it as a maximum.
If target profile is not specified, MediaCodec returns "most basic" profile (e.g. Baseline for AVC), even if hardware supports higher level (e.g. Main or High for AVC) profiles. This results lower quality output than device is capable of. This functionality is meant to fix that. 
One possible caveat is that this logic simply uses a list of codes and does not account for hardware capabilities, so transcoding may potentially fail if device capabilities are exceeded. We are hoping to address this in future work.
> Pick highest supported codec profile

- litr/src/main/java/com/linkedin/android/litr/transcoder/PassthroughTranscoder.java
Sometimes MediaFormat doesn't contain max buffer size (it is an optional field). In those cases we fall back to a 1 Mb buffer to avoid an NPE.
> Fall back to 1 Mb buffer in PassthroughTranscoder

- litr-demo/build.gradle
- litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoCase.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/VideoFilterPreviewFragment.java
- litr-demo/src/main/res/layout/fragment_video_filter_preview.xml
- litr-demo/src/main/res/values/strings.xml
- litr/src/main/java/com/linkedin/android/litr/preview/PreviewEglConfigChooser.java
- litr/src/main/java/com/linkedin/android/litr/preview/PreviewEglContextFactory.java
- litr/src/main/java/com/linkedin/android/litr/preview/VideoFilterPreviewView.java
- litr/src/main/java/com/linkedin/android/litr/preview/VideoPreviewRenderer.java
A combination of custom implementations of `GLSurfaceView` and `GlSurfaceView.Renderer` that allows previewing the effect of `GlFrameRenderFilter` on a video. Renderer creates a `Surface`, which video player (such as ExoPlayer) can render onto. This surface effectively becomes an analog of `Decoder`'s output surface, which `GlFrameRenderFilter` is then applied to.
> Video filter preview functionality

- litr-demo/src/main/java/com/linkedin/android/litr/demo/VideoFilterPreviewFragment.java
- litr/src/main/java/com/linkedin/android/litr/preview/VideoPreviewRenderer.java
It is more flexible to use `SurfaceTexture` in a callback, rather than `Surface`. If `Surface` needs to be used, it is very easy to create it from a `SurfaceTexture`, and `SurfaceTexture` can be used in camera preview.
> Make preview renderer call back with SurfaceTexture instead of Surface

- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java
- litr-demo/src/main/res/layout/fragment_transcode_video_gl.xml
- litr/src/main/java/com/linkedin/android/litr/io/MediaExtractorMediaSource.java
- litr/src/main/java/com/linkedin/android/litr/io/MediaRange.java
- litr/src/main/java/com/linkedin/android/litr/io/MediaSource.java
- litr/src/main/java/com/linkedin/android/litr/render/PassthroughSoftwareRenderer.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/PassthroughTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/TrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoder.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoderShould.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/PassthroughTranscoderShould.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoderShould.java
New functionality that allows selecting a range within MediaSource (effectively allowing to trim media):
- new MediaRange data is introduced to define range (more verbose than Java `Range`), values are in microseconds to match MediaSource.seekTo
- if no range is specified, default range is passed in, which contains entire MediaSource duration (0 to Long.MAX_VALUE)
- MediaExtractorMediaSource automatically seeks to range start, to speed up transformation
- track transcoders decide which frames to process and which to discard
- frame presentation times are modified when trimming
Source selection is only supported through APIs that use MediaSource. Support in basic API will be added in upcoming PR.
Behavior is verified using manual testing. Unit tests are coming in upcoming PR.
> Support for trimming media

- litr/src/main/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoder.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoderShould.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/PassthroughTranscoderShould.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoderShould.java
New unit tests for all three track transcoders (video, audio, passthrough), which test behavior for cases when frames are outside/inside of media selection range.
> Media trimming unit tests

- litr/src/main/java/com/linkedin/android/litr/render/PassthroughSoftwareRenderer.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoder.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoderShould.java
Audio transcoder was passing in time stamp to its renderer in microseconds, directly from BufferInfo.presentationTimeUs. According to `Renderer.render` interface spec, timestamp must be in nanoseconds. Fixing this. 
Also, using same `TimeUnit` util in video track transcoder.
> Pass presentation time to audio renderer in nanoseconds

- litr/src/main/java/com/linkedin/android/litr/utils/TranscoderUtils.java
- litr/src/test/java/com/linkedin/android/litr/TransformationJobShould.java
- litr/src/test/java/com/linkedin/android/litr/utils/TranscoderUtilsShould.java
Whenever the library estimates the target media's size, it always checks for the track durations, not the user defined `MediaRange`s. This PR adds the missing functionality which will improve the size estimation when video trimming is involved.
PR includes a test where the trimmed (half the mocked track length) estimated size is half of the default track size.
> Take MediaRange into account when estimating target size

- litr/src/main/java/com/linkedin/android/litr/codec/MediaCodecDecoder.java
- litr/src/main/java/com/linkedin/android/litr/codec/MediaCodecEncoder.java
- litr/src/main/java/com/linkedin/android/litr/utils/CodecUtils.java
[LiTr-85](https://github.com/linkedin/LiTr/issues/85)
While testing the new trimming capabilities in different devices I noticed that the `TrackTranscoderException.Error.ENCODER_NOT_FOUND` was thrown in most of my test devices. While doing few more tests and debugging I think that the issue might be originated by the way the method `isFormatSupported` in `MediaCodecInfo` from the Android media API is implemented to find out if a MediaFormat is supported on a device.
'MediaCodecList` class in LiTr has the following method:
```
private String findCodecForFormat(boolean encoder, MediaFormat format) {
String mime = format.getString(MediaFormat.KEY_MIME);
for (MediaCodecInfo info: mCodecInfos) {
if (info.isEncoder() != encoder) {
continue;
}
try {
MediaCodecInfo.CodecCapabilities caps = …
```
> Encoder and/or decoder not found exception erroneously thrown #85

- litr/src/main/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoder.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoderShould.java
Last audio frame (with EOS flag) has a presentation time of -1, which causes an `IllegalArgumentException` on `MediaMuxer` when we try to write it. This was not happening on newer devices, because buffer size was zero, which prevents `AudioTrackTranscoder` from writing. But on some older devices (such as Samsung Galaxy S5) buffer size would be non-zero, which would make transcoding fail. 
To fix that, we reverse the check - we check if audio frame is EOS before doing any other checks, and not write EOS frame at all.
> Not try to write encoded audio frame with negative presentation time

- litr/src/main/java/com/linkedin/android/litr/codec/MediaCodecDecoder.java
- litr/src/main/java/com/linkedin/android/litr/codec/MediaCodecEncoder.java
- litr/src/main/java/com/linkedin/android/litr/utils/CodecUtils.java
We have been using either getting by config or getting by type. Now we are getting by config first, and if that fails we attempt to get by type:
- fallback is controlled by passing a flag. This is done for the time being, since we want to measure if this fix makes an impactful change. By default, flag is `true` so fallback is enabled.
- logic to get and configure an instance of `MediaCodec` has been parametrized and moved into `CodecUtils` 
- and earlier fix by @luix has been temporarily reverted, to get cleaner measurement of getting by format vs. getting by type
> Fallback to getting codec by type when getting by config fails

- litr/src/main/java/com/linkedin/android/litr/TransformationJob.java
- litr/src/main/java/com/linkedin/android/litr/codec/MediaCodecDecoder.java
- litr/src/main/java/com/linkedin/android/litr/render/PassthroughSoftwareRenderer.java
- litr/src/test/java/com/linkedin/android/litr/render/PassthroughSoftwareRendererShould.java
1. Fix an issue in renderFrame() method inside PassthroughSoftwareRenderer class, where it throws a BufferOverflowException when the InputBuffer's size is larger than the OutputBuffer's size.
2. Add a try-catch to some release() methods, where it's safe to catch the exception and not throw it, also to not make wrong behavior where the onError method of TransformationListener will not be called.
3. This pull request will fix the opened issue in litr, https://github.com/linkedin/LiTr/issues/102
> Fix renderFrame logic in PassthroughSoftwareRenderer

- litr/src/main/java/com/linkedin/android/litr/render/PassthroughSoftwareRenderer.java
- litr/src/test/java/com/linkedin/android/litr/render/PassthroughSoftwareRendererShould.java
- Make the default FRAME_WAIT_TIMEOUT equals to zero, because on some device the previous value cause a very very long processing time
- Add the ability to configure the FRAME_WAIT_TIMEOUT in the constructor as a parameter
> Make the default FRAME_WAIT_TIMEOUT equals to zero

- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java
- litr/src/main/java/com/linkedin/android/litr/codec/MediaCodecDecoder.java
- litr/src/main/java/com/linkedin/android/litr/codec/MediaCodecEncoder.java
- litr/src/main/java/com/linkedin/android/litr/utils/CodecUtils.java
Enhance the logic for finding a media codec for a media format, where sometimes the findEncoderForFormat/findDeccoderForFormat or createEncoderByType/createDecoderByType methods will return the first MediaCodec in the available media codecs that could support the media type, but this codec may not be able to configure the media format, so the fix here is to get all available codecs that support the mimeType, and iterate over them to check which codec could configure the media format and return it
> Enhance the logic for finding a media codec for a media format

- litr/src/main/java/com/linkedin/android/litr/codec/MediaCodecDecoder.java
- litr/src/main/java/com/linkedin/android/litr/codec/MediaCodecEncoder.java
- litr/src/main/java/com/linkedin/android/litr/utils/CodecUtils.java
With all experimentation done, we can now remove flags for different ways of manually finding compatible codecs. We can also remove supporting logic.
> Remove fallback codec lookup configuration flags

- litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoCase.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/EmptyVideoFragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java
- litr-demo/src/main/res/layout/fragment_empty_video.xml
- litr-demo/src/main/res/values/strings.xml
- litr/src/main/java/com/linkedin/android/litr/codec/PassthroughDecoder.kt
- litr/src/main/java/com/linkedin/android/litr/io/MockVideoMediaSource.kt
- litr/src/test/java/com/linkedin/android/litr/codec/PassthroughDecoderShould.kt
Adding two new classes that will let us do some powerful media transformations:
- `MockVideoMediaSource` is an implementation of `MediaSource` that acts as a source with a single video track of a certain duration. Client defines properties of this track by passing in a `MediaFormat` with necessary metadata values. 
- `PassthroughDecoder` is an implementation of `Decoder` which simply outputs input frames in the order it received them. If running in hardware accelerated mode, it also triggers a GL draw call when output frame is released with a request to render a frame.
We use these two new classes in a new demo case to create a 5 second "empty" video. Optionally we can use a still background image, turning that into a video.
> Implementation of MockVideoMediaSource and PassthroughDecoder

- litr/src/main/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/PassthroughTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoder.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoderShould.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/PassthroughTranscoderShould.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoderShould.java
Zero bytes can be read from the data source in some valid cases. This change treats 0 bytes read as a valid scenario that does not signal EOS.
Subjectively, the issue appears when transcoding the metadata track of a 60fps mp4 recorded on a Pixel 5: `readSampleData` returns 0 bytes read on every other read. On the other hand, video with a 30fps video stream recorded on the same device didn't present this problem (i.e. sample size was always > 0).
I'm not excluding that the issue might have another underlying cause or solution, but the [readSampleData docs](https://developer.android.com/reference/android/media/MediaExtractor#readSampleData(java.nio.ByteBuffer,%20int)) indicate that the return value is "the sample size, **or** -1 if no more samples are available". Thus, 0 can be considered a …
> Allow non-negative reads from source buffer during transcoding

- litr/src/main/java/com/linkedin/android/litr/render/GlVideoRenderer.java
- litr/src/main/java/com/linkedin/android/litr/render/Renderer.java
`GlVideoRenderer.hasFilters()` always returned true, since it always had a `DefaultFrameRendererFilter` 
Intended behavior of `hasFilters()` method is to see if renderer has user provided filters, which would mean that user is modifying video frames, which in turn means that we cannot use a `PassthroughTrackTranscoder`. Fixing this now.
> Fix GlVideoRenderer.hasFilters() logic

- litr-demo/src/main/java/com/linkedin/android/litr/demo/EmptyVideoFragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/FreeTransformVideoGlFragment.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/MockTranscodeFragment.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/MuxVideoAndAudioFragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/SquareCenterCropFragment.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/TranscodeVideoGlFragment.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/VideoFiltersFragment.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/VideoWatermarkFragment.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/MediaTransformationListener.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/SharedMediaStoragePublisher.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TargetMedia.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java
- litr-demo/src/main/java/com/linkedin/android/litr/utils/TransformationUtil.java
- litr-demo/src/main/res/layout/fragment_empty_video.xml
- litr-demo/src/main/res/layout/fragment_mux_video_audio.xml
- litr-demo/src/main/res/layout/fragment_square_center_crop.xml
- litr-demo/src/main/res/layout/fragment_transcode_video_gl.xml
- litr-demo/src/main/res/layout/fragment_video_filters.xml
- litr-demo/src/main/res/layout/fragment_video_overlay_gl.xml
- litr-demo/src/main/res/layout/fragment_video_watermark.xml
With Android Q+, we should no longer use `Environment.getExternalStoragePublicDirectory`, because it is deprecated and will throw when attempting IO with files in that directory.
The approach here is:
1. Write all video files to the files dir owned by demo app.
2. When transcoding is done, create a MediaStore entry and copy finished video to the content URI, deleting original file.
This keeps changes localized to the demo app.
We can also consider adding UI (checkbox or button) to explicitly specify if step #2 should happen, because it has potential to pollute the user's device with a lot of transcoded videos.
> Store videos locally for transcoding, create MediaStore entries when transcoded successfully

- litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java
Removing this, since setting the profile here causes some codecs to fail -- the codec used should automatically select the best profile
> Do not set "profile" (MediaCodec.KEY_PROFILE) on the encoder

- litr-demo/src/main/java/com/linkedin/android/litr/demo/BaseTransformationFragment.java
- litr-demo/src/main/java/com/linkedin/android/litr/utils/TrackMetadataUtil.java
- litr/src/main/java/com/linkedin/android/litr/io/MockVideoMediaSource.kt
- litr/src/main/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/utils/MediaFormatUtils.kt
This PR provides a safer way to retrieve frame rate and I-Frame interval from MediaFormat, since those values can be stored as either float or int (see [here](https://developer.android.com/reference/android/media/MediaFormat#KEY_FRAME_RATE), [here](https://developer.android.com/reference/android/media/MediaFormat#KEY_I_FRAME_INTERVAL)).
To reduce the scope of changes, this PR doesn't change the type of these values in the lib or the demos -- only provides minor safety for retrieving them. As a result, the way those values are used should remain unchanged (i.e. continue to use int)
When the output format is set (`MediaCodec.INFO_OUTPUT_FORMAT_CHANGED`), we obtain the target format from the encoder. The format can contain either float or int values for the above-keys, so reading as integer …
> Handle float frame rate or interval in MediaFormat

- litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java
We added new `MediaTransformer` methods to `transform` media that accept `List<TrackTransform>` and `TranformationOptions`, but didn't add their `getEstimatedVideoSize` counterparts. Fixing that. 
Also, deprecating an existing size estimation method that doesn't accept `TransformationOptions`. If user don't have a `MediaRange`, they should pass `null` explicitly.
> Add new target size estimation APIs to MediaTransformer

- litr/src/main/java/com/linkedin/android/litr/utils/TranscoderUtils.java
- litr/src/test/java/com/linkedin/android/litr/utils/TranscoderUtilsShould.java
Duration estimation had a bug, it didn't work when media range started at non-zero and ended at Long.MAX_VALUE
> Fix for incorrect size estimation with range

- litr/src/main/java/com/linkedin/android/litr/render/AudioRenderer.kt
- litr/src/main/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoder.java
Basic implementation of audio renderer. Doesn't do much yet (no resampling, no mixing), but does couple of important things:
- has a render queue which queues up audio frames in order, while encoder is busy and cannot accept new frames
- handles the case when size of decoded buffer is larger than size of encoder's input buffer by sending decoded buffer into encoder in several parts
Not having render queue in existing audio renderer does result in dropped frames which manifests as distorted audio.
> New AudioRenderer implementation, with a render queue

- litr/build.gradle
- litr/src/main/cpp/CMakeLists.txt
- litr/src/main/cpp/audio-resampler.cpp
- litr/src/main/cpp/oboe_resampler/CMakeLists.txt
- litr/src/main/cpp/oboe_resampler/HyperbolicCosineWindow.h
- litr/src/main/cpp/oboe_resampler/IntegerRatio.cpp
- litr/src/main/cpp/oboe_resampler/IntegerRatio.h
- litr/src/main/cpp/oboe_resampler/KaiserWindow.h
- litr/src/main/cpp/oboe_resampler/LinearResampler.cpp
- litr/src/main/cpp/oboe_resampler/LinearResampler.h
- litr/src/main/cpp/oboe_resampler/MultiChannelResampler.cpp
- litr/src/main/cpp/oboe_resampler/MultiChannelResampler.h
- litr/src/main/cpp/oboe_resampler/PolyphaseResampler.cpp
- litr/src/main/cpp/oboe_resampler/PolyphaseResampler.h
- litr/src/main/cpp/oboe_resampler/PolyphaseResamplerMono.cpp
- litr/src/main/cpp/oboe_resampler/PolyphaseResamplerMono.h
- litr/src/main/cpp/oboe_resampler/PolyphaseResamplerStereo.cpp
- litr/src/main/cpp/oboe_resampler/PolyphaseResamplerStereo.h
- litr/src/main/cpp/oboe_resampler/README.md
- litr/src/main/cpp/oboe_resampler/SincResampler.cpp
- litr/src/main/cpp/oboe_resampler/SincResampler.h
- litr/src/main/cpp/oboe_resampler/SincResamplerStereo.cpp
- litr/src/main/cpp/oboe_resampler/SincResamplerStereo.h
- litr/src/main/java/com/linkedin/android/litr/render/AudioResampler.kt
- litr/src/main/java/com/linkedin/android/litr/render/OboeAudioResampler.kt
Pulling Oboe resampler (https://github.com/google/oboe/tree/main/src/flowgraph/resampler) and using it to resample audio. Oboe is fast (all native cod, supports variety of high quality resampling algorithms and can increase as well as decrease sample rate.
- Resampler is standalone by design to make it easy to build and use it via JNI. 
- As recommended, Oboe resampler classes are pulled into JNI and built using CMake
- `audio-resampler` jni class is introduced to use Oboe from Java layer. It has most of frame-by-frame audio resampling logic
- Java layer is implemented as a standalone class, which will be used in `AudioRenderer` in upcoming PR.
> Use Oboe to resample audio

- litr/src/main/java/com/linkedin/android/litr/render/AudioRenderer.kt
There is an easier way to copy input audio buffer to output one. Instead of a using `array` to do a bulk copy, we simply use `get` and `put` methods in a loop. This reduces lines of code and has an additional benefit of supporting direct buffers, which may return `null`. We will need this support in upcoming resampling support.
> Simpler input buffer into output buffer copy in AudioRenderer

- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java
- litr/src/main/java/com/linkedin/android/litr/render/AudioRenderer.kt
- litr/src/main/java/com/linkedin/android/litr/render/AudioResamplerFactory.kt
- litr/src/main/java/com/linkedin/android/litr/render/OboeAudioResampler.kt
- litr/src/main/java/com/linkedin/android/litr/render/PassthroughResampler.kt
- litr/src/main/java/com/linkedin/android/litr/transcoder/TrackTranscoderFactory.java
With `OboeAudioResampler` implemented, we can now add audio resampling support in `AudioRenderer`:
- current logic of copying source `Frame` into target one is abstracted out into `PassthroughResampler`
- `AudioResamplerFactory` is added to create correct implementation of `AudioResampler` depending if resampling support is needed
- `AudioResampler` is now used by default
> Add resampling support in AudioRenderer

- litr/src/main/java/com/linkedin/android/litr/io/WavMediaTarget.kt
Implementation of `MediaTarget` interface which writes audio track into WAV container:
- only one audio track is accepted, given that it is in correct (PCM) format and has necessary parameters
- header writing/updating implementation is taken from https://gist.github.com/kmark/d8b1b01fb0d2febf5770
> MediaTarget implementation for WAV audio container

- litr/src/main/java/com/linkedin/android/litr/filter/BufferFilter.kt
- litr/src/main/java/com/linkedin/android/litr/render/AudioRenderer.kt
Similar to video GL filters, adding support for audio filters:
- introducing a new `BufferFilter` interface that is called to modify `Frame` contents, meant to be used for any `Renderer` in a buffer mode
- `AudioRenderer` can now accept a list of filters and apply them in order.
- No actual filters are yet implemented
> Capability to apply filters in AudioRenderer

- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TargetMedia.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java
- litr-demo/src/main/res/layout/fragment_transcode_audio.xml
- litr-demo/src/main/res/values/strings.xml
- litr/src/main/java/com/linkedin/android/litr/codec/Encoder.java
- litr/src/main/java/com/linkedin/android/litr/codec/PassthroughBufferEncoder.kt
- litr/src/test/java/com/linkedin/android/litr/codec/PassthroughBufferEncoderShould.kt
An implementation of `Encoder` which simply passes input `ByteBuffer`s into output, with no modification. Useful when raw decoded frames are needed - for inspection, or to write audio frames into a WAV file. 
Demo of writing audio into WAV file is included.
> Passthrough ByteBuffer encoder

- litr/src/main/java/com/linkedin/android/litr/render/AudioRenderer.kt
Initially `AudioRenderer` did not support filters, so `hasFilters` defaulted to returning `false`. Fixing this oversight.
> Fix hasFilters method logic in AudioRenderer

- litr/src/main/java/com/linkedin/android/litr/frameextract/FrameExtractJob.kt
- litr/src/main/java/com/linkedin/android/litr/frameextract/VideoFrameExtractor.kt
- litr/src/main/java/com/linkedin/android/litr/frameextract/queue/ComparableFutureTask.kt
Whenever a frame extraction gets cancelled by its request id, there were some cases when a subsequent extract call for the same request id was not reporting any result/error/cancellation.
The initial cancellation call was fired when the extraction job hadn't started yet, this was causing the job never being interrupted and never getting into a point of triggering a cancellation listener. The cancellation listener is the one in charge of removing the job from the `activeJobMap`, so since it was never removed, subsequent calls with the same request id were immediately discarded because the job still was in the `activeJobMap`.
Add a `isStarted` property to the `FrameExtractJob`, which gets set to `true` right at the beginning of the `run` method of the `Runnable`. This property is exposed to …
> Ensure non-started jobs are removed from jobs map when stopping

- litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java
We have a `MediaMuxer` constructor that accepts a `Uri` and uses a `FileDescriptor` on API 26+. It was not exposed in non-track `transform` method. Now adding a method that accepts a Uri which uses that constructor. This should help with using scoped storage framework on Android 10+, which works with `FileDescriptor`s.
> Add new transform method that accepts output URI

- litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java
- litr/src/main/java/com/linkedin/android/litr/test/MockMediaTransformer.java
Removing `@Deprecated` methods from `MediaTransformer`. They have been deprecated for a while.
> Remove deprecated MediaTransformer methods

- litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoCase.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/TranscodeToVp9Fragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java
- litr-demo/src/main/res/layout/fragment_video_vp9.xml
- litr-demo/src/main/res/values/strings.xml
- litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java
Implementation of support for encoding video to VP8/VP9:
- version gated for Lollipop
- clients could already encode into VP8/VP9 via track transform API, this PR adds that support for simple `transform` API
- if audio track format is not specified, audio will be transcoded to Opus codec, with source encoding parameters (channel count, bitrate, etc.)
- WebM container will be automatically set if target video track format is VP8 or VP9
> Support for transcoding video to VP8/VP9

- litr/src/main/java/com/linkedin/android/litr/render/GlVideoRenderer.java
Just a wrong degree to radian formula
> Fixed angle computation

- litr/src/main/java/com/linkedin/android/litr/render/AudioRenderer.kt
- litr/src/main/java/com/linkedin/android/litr/utils/MediaFormatUtils.kt
Currently `AudioRenderer` initializes `AudioProcessor` once, when created. What happens in reality sometimes (as reported in https://github.com/linkedin/LiTr/issues/188) audio track format reported in track metadata does not correspond to actual track format reported by MediaCodec. This causes audio processing to fail because we initialize `AudioProcessor` for one set of sampling rate / channel count combination but actual sampling rate / channel count could be different which causes a `BufferOverflowException`. 
Solution is to re-create `AudioProcessor` each time either source or target format changes. This ensures that it is configured correctly.
> Recreate AudioProcessor on source/target audio format change

- litr-demo/src/main/java/com/linkedin/android/litr/demo/TranscodeVideoGlFragment.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/AudioVolumeConfig.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/SourceMedia.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java
- litr-demo/src/main/res/layout/fragment_transcode_video_gl.xml
- litr-demo/src/main/res/layout/section_audio_volume.xml
- litr-demo/src/main/res/values/strings.xml
- litr-filters/src/main/java/com/linkedin/android/litr/filter/audio/VolumeFilter.kt
Our first audio filter. Simplest one, changes track volume:
- takes a non-negative double value
- 0 volume silences the track
- volume 1 doesn't really change anything
- value <1 reduces the volume
- value >1 increases the volume
- actual sample value change is exponential, since volume perception is logarithmic
> Audio filter that changes track volume

- litr/src/main/java/com/linkedin/android/litr/frameextract/VideoFrameExtractor.kt
Collection of jobs was being modified while iterating.
To reproduce, run the demo and:
- Tap Extract Video Frames
- Pick a video
- Tap Extract
- While frames are being extracted, tap Extract again
With the fix, the exception will no longer be thrown, and extracting will restart as expected.
> Frame extractor: fix ConcurrentModificationException when removing jobs

- litr/src/main/java/com/linkedin/android/litr/TransformationJob.java
I have seen the `release()` call hang in certain cases when processing failed as a result of which the listener
callback never invoked. Which then broke our internal app logic as the processing seemed stuck forever. 
I think it's better to first invoke the callback so that LiTr users can at least somehow propagate the error to end users or log the associated exception.
How to test:
1. It's hard to test, but I was able to simulate this on simulator with API 26 (arm64). Granted all video processing than seems broken as the emulator likely simply doesn't support it, but if you open LiTr demo there and try to encode any video it just appears stuck. 
This video shows a recording of the issue in Android Studio. I set a breakpoint to manifest that the listener is never hit when it gets stuck in …
> Notify TransformationListener before releasing TransformationJob

- litr/src/main/cpp/audio-processor.cpp
We were allocating native buffers for Oboe audio processor on each frame and not de-allocating them, as was pointed out in https://github.com/linkedin/LiTr/issues/201 
Instead, now we are allocating them when we initialize the resampler (when we know the buffer size) and deallocating them when we release the resampler.
> Allocate/deallocate native input/output buffers on init/release

- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TargetTrack.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TargetVideoTrack.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TranscodingConfigPresenter.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/view/AudioTrackViewHolder.java
- litr-demo/src/main/res/layout/item_audio_track.xml
- litr-demo/src/main/res/values/strings.xml
- litr-filters/src/main/java/com/linkedin/android/litr/filter/audio/AudioOverlayFilter.kt
- litr/src/main/java/com/linkedin/android/litr/render/AudioProcessorFactory.kt
- litr/src/main/java/com/linkedin/android/litr/utils/ByteBufferPool.kt
Implementation of audio overlay filter, which "mixes in" an audio track over audio track(s) of source media. This functionality  could be used to add a voiceover, or background music.
- It is a pretty complicated filter, that reads an audio frame from a uri, decodes it, resamples/channel mixes it to match the media audio configuration, then "mixes" it with the audio track frame. 
- When reading overlay frames, we make sure that we have enough samples to apply to all audio frame samples. We queue those samples in internal render queue.
- When mixing in overlay frames, we consume overlay samples from the render queue until all audio frame samples are modified.
- We use `AudioProcessorFactory` and `BufferPool` from main `litr` library, so they had to be made public.
> Implementation of audio overlay filter

- litr-demo/src/main/res/layout/item_video_track.xml
- litr/src/main/java/com/linkedin/android/litr/render/FrameDropper.kt
- litr/src/main/java/com/linkedin/android/litr/transcoder/TrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoder.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/FrameDropperShould.kt
This PR adds a simple `FrameDropper` as recommended by alexvaliskov in [issue #120](https://github.com/linkedin/LiTr/issues/120#issuecomment-859318538). This allows users to reduce the target video's frame rate, which has been a requested feature for some time.
I've also included some tests and the ability to alter the frame rate in the demo app, which makes it easy to runtime test this feature.
> Add ability to reduce the target video's frame rate

- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java
- litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java
- litr/src/main/java/com/linkedin/android/litr/TransformationOptions.java
- litr/src/main/java/com/linkedin/android/litr/exception/MediaTargetException.java
There were multiple requests to support removing audio track(s) when using non-`TrackTransform` based `transform` API: https://github.com/linkedin/LiTr/issues/196
We are adding a new `removeAudio` flag to `TransformationOptions` which does just that.
> Add TransformationOptions flag to remove audio track(s)

- litr/src/main/java/com/linkedin/android/litr/utils/TranscoderUtils.java
- litr/src/test/java/com/linkedin/android/litr/TransformationJobShould.java
Bitrate extraction when estimating size was unsafe and could throw a 'NullPointerException' for metadata tracks that wouldn't have a bitrate in their `MediaFormat`. This happened in https://github.com/linkedin/LiTr/issues/210 , for example. Now using safe method that checks for presence of the key.
> Fix for incorrect bitrate extraction in size estimation

- litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java
When we were creating `MediaFormat` in cases when `targetMediaFormat` was `null` (keep source format) but overlays were present, we did not populate frame rate. This could be problematic when configuring an encoder, they usually need frame rate to be present. 
Now populating it with either source format value, or default of 30 if source format does not have it.
> Use source (or default) frame rate when creating video MediaFormat

- litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java
When creating `TrackTransform`s for simple `transform` method, we did configure `TrackTransform` for generic tracks correctly. For example, target `MediaFormat` would have no fields, which would cause an exception because `TrackTranscoderFactory` expects each track to have a mime type. Fixing this now by explicitly setting `null` target format, thus enforcing using `PassthroughTrackTranscoder` for generic (not video or not audio) tracks.
> Use null target MediaFormat for generic tracks

- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java
- litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java
- litr/src/main/java/com/linkedin/android/litr/TransformationOptions.java
Similar to ability to remove audio tracks via `TransformationOptions` parameter, adding an option to remove metadata tracks. This is useful for use cases like transcoding to VP9 which does not support metadata tracks.
> Parameter to remove metadata tracks

- litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java
- litr/src/main/java/com/linkedin/android/litr/MimeType.java
We had special handling for VP8/VP9 video transcoding when we enforced audio to OPUS codec. Recently an issue #215  was reported where transcoding from MOV to MP4 failed because MOV file contained an audio track in `audio/raw` format which did not have an encoder, which could be fixed by enforcing AAC codec for AVC/HEVC videos. In this PR we fix both problems by introducing more general approach to audio codec enforcement:
- we use video MIME type to determine if audio codec is compatible with video codec in target video. If not compatible, we transcode audio as well if incompatible audio is asked to be coped to target "as is"
- for H.264 formats (AVC, HEVC) `audio/raw` is listed as incompatible and will be transcoded to AAC
- for VP8/VP9 format any non-OPUS or non-VORBIS audio track is …
> Enforce transcoding of incompatible audio track(s)

- litr/src/main/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoder.java
When trimming, presentation time of an audio frame was not adjusted with respect to trim start time. This caused odd progress values (>1, starting at large non-zero values, etc.) reported in #223 
This is now fixed by adjusting the presentation time in audio frame before passing it to an audio processor.
> Fix for incorrect audio frame presentation time when trimming

- litr/src/main/java/com/linkedin/android/litr/codec/MediaCodecEncoder.java
If video frame rate is not provided in target `MediaFormat` encoding will likely fail. To prevent that, let's default to 30 fps.
Bonus fix: we were setting color format for all target formats (including audio), so let's do that only for video.
> Default to 30 fps target frame rate if parameter is missing

- litr-demo/src/main/AndroidManifest.xml
- litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoCase.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/RecordAudioFragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java
- litr-demo/src/main/res/layout/fragment_audio_record.xml
- litr-demo/src/main/res/values/strings.xml
- litr/src/main/java/com/linkedin/android/litr/io/AudioRecordMediaSource.kt
I'm hoping to introduce Camera support as an input into Litr. This would allow scenarios where the raw audio/video is not sourced from a static file, but instead coming from a "live" source. I am planning the following, separate, pull requests:
- Audio Record Support: Ability to pull raw PCM from an audio source (e.g. microphone) to mux with video from another source
- External Surface Support: Ability to expose the raw surface that is used by the filter pipeline, allowing some other component (e.g. Camera2, CameraX, 3rd party library) to render directly into this. This will essentially bypass the Demux/Decode steps of the pipeline.
- Camera2/CameraX Support: Helper classes/source for most common camera source scenarios.
This first PR covers Audio Record Support. It introduces a new …
> Implement AudioRecord support for audio track

- litr/src/main/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/PassthroughTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/TrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoder.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoderShould.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/PassthroughTranscoderShould.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoderShould.java
One of recent bug reports (#216 ) has an interesting use case - metadata track that starts after selection range end. Current logic never advances far past the end of selection, so we never process that metadata track thus "hanging" indefinitely.
Changing trim logic to handle cases like this:
- introduce new "end of range" transcoder state. It is similar to "end of stream" state, but it is less "final" - track transcoder is still allowed to advance to next track or end of current track.
- new logic that correctly detects "end of range" and "end of stream" states
- track transcoder's "end of range" state is still reported as "end of stream" to `TransformationJob`, to indicate that processing of that track is done and it is ok to complete the job.
- if `TransformationJob` is not completed, …
> Allow transcoders advance to next track or EoS past selection end

- litr-demo/src/main/AndroidManifest.xml
- litr-demo/src/main/java/com/linkedin/android/litr/demo/CameraSizes.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoCase.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/RecordCamera2Fragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/RecordCameraPresenter.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/fragment/RecordAudioFragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/view/AutoFitSurfaceView.kt
- litr-demo/src/main/res/layout/fragment_camera2_record.xml
- litr-demo/src/main/res/values/strings.xml
- litr/src/main/java/com/linkedin/android/litr/MimeType.java
- litr/src/main/java/com/linkedin/android/litr/io/AudioRecordMediaSource.kt
- litr/src/main/java/com/linkedin/android/litr/io/Camera2MediaSource.kt
- litr/src/main/java/com/linkedin/android/litr/io/CaptureMediaSource.kt
This PR introduces two new MediaSources:
- `ExternalMediaSource`: This provides the owner direct access to the Surface that will be used as the input into any configured filters, followed by the encoder. The reason for this is to allow non-file based sources of video.
- `Camera2MediaSource`: This utilises the `ExternalMediaSource` and uses Android's Camera2 APIs to render from the camera to the input Surface. This is being combined with the previously landed `AudioRecordMediaSource` that is adding the audio stream. This demonstrates a Camera to File example.
Also, one thing to note is that the ExternalMediaSource does not support cropping. It expects the source aspect ratio to match that of the file/target aspect ratio. We could either keep this as a hard constraint, or we could introduce …
> Implement Camera2 support as a MediaSource

- litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoCase.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/fragment/CameraSizes.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/fragment/RecordAudioFragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/fragment/RecordCamera2Fragment.kt
It looks like I landed the `RecordCamera2Fragment` **after** the fragments had been moved into a new / dedicated package. This PR simply moves these new classes to their suitable location, along with fixing the imports.
> Move RecordCamera2Fragment to fragment package

- litr/src/main/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/TrackTranscoder.java
- litr/src/main/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoder.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/AudioTrackTranscoderShould.java
- litr/src/test/java/com/linkedin/android/litr/transcoder/VideoTrackTranscoderShould.java
On newer versions of Android `MediaFormat` produced by `Encoder` might not contain some useful values (such as duration) even if they were passed in. When such `MediaFormat` is added to `MediaTarget` it will produce a video with missing useful metadata, as reported in #222 
We are fixing this by populating missing duration and language metadata from source `MediaFormat` in encoder output `MediaFormat` before adding a track in `MediaTarget`. 
Assertions are added in unit tests for new logic.
> Add missing duration target track metadata when adding track to muxer

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- litr-demo/build.gradle
- litr-demo/src/main/AndroidManifest.xml
- litr-demo/src/main/java/com/linkedin/android/litr/demo/MainActivity.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/RecordAudioPresenter.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/RecordCameraPresenter.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/fragment/CameraSizes.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/fragment/EmptyVideoFragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/fragment/MuxVideoAndAudioFragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/fragment/RecordAudioFragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/fragment/RecordCamera2Fragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/fragment/TranscodeAudioFragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/fragment/TranscodeToVp9Fragment.kt
- litr-demo/src/main/res/values/strings.xml
- litr-filters/build.gradle
- litr-filters/src/main/AndroidManifest.xml
- litr-filters/src/main/java/com/linkedin/android/litr/filter/audio/AudioOverlayFilter.kt
- litr/build.gradle
- litr/src/main/AndroidManifest.xml
- litr/src/main/java/com/linkedin/android/litr/MarshallingTransformationListener.java
- litr/src/main/java/com/linkedin/android/litr/io/AudioRecordMediaSource.kt
- litr/src/main/java/com/linkedin/android/litr/io/Camera2MediaSource.kt
- litr/src/main/java/com/linkedin/android/litr/io/CaptureMediaSource.kt
- litr/src/main/java/com/linkedin/android/litr/io/MediaExtractorMediaSource.java
- litr/src/main/java/com/linkedin/android/litr/io/WavMediaTarget.kt
- litr/src/main/java/com/linkedin/android/litr/render/GlSingleFrameRenderer.kt
I started looking into fleshing out CameraX support but found when adding the dependency, there was a miss-match of kotlin version that reported warnings. I then went down a rabbit hole to see what would be required to upgrade. These were the changes I ended up making, so thought I would raise a PR for consideration. This also includes some fixes for the warnings coming identified by the upgraded build tools.
This change includes:
- Updating Kotlin version from 1.4.32 -> 1.7.20
- Updating AGP 7.1.2 -> 7.3.1
- Updating compileSdkVersion 30 -> 33
> Upgrade Build Tools / SDK / Kotlin

- litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoCase.java
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/RecordCameraPresenter.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TranscodeVideoGlPresenter.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/fragment/NativeMuxerCameraFragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/fragment/NativeMuxerTranscodeFragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/fragment/RecordCamera2Fragment.kt
- litr-demo/src/main/java/com/linkedin/android/litr/demo/fragment/TranscodeVideoGlFragment.java
- litr-demo/src/main/res/layout/fragment_camera2_record.xml
- litr-demo/src/main/res/layout/fragment_transcode_video_gl.xml
- litr-demo/src/main/res/values/strings.xml
- litr-muxers/src/main/cpp/MediaMuxer.cpp
- litr-muxers/src/main/java/com/linkedin/android/litr/muxers/MediaFormatEx.kt
- litr-muxers/src/main/java/com/linkedin/android/litr/muxers/NativeLogger.kt
- litr-muxers/src/main/java/com/linkedin/android/litr/muxers/NativeMediaMuxer.kt
- litr-muxers/src/main/java/com/linkedin/android/litr/muxers/NativeMediaMuxerMediaTarget.kt
- litr-muxers/src/main/java/com/linkedin/android/litr/muxers/NativeMuxersLib.kt
- litr-muxers/src/main/java/com/linkedin/android/litr/muxers/NativeOutputFormats.kt
- litr/src/main/java/com/linkedin/android/litr/MimeType.java
- litr/src/main/java/com/linkedin/android/litr/exception/MediaTargetException.java
- litr/src/main/java/com/linkedin/android/litr/io/MediaMuxerMediaTarget.java
- litr/src/main/java/com/linkedin/android/litr/io/MediaTargetSample.kt
After adding ffmpeg and the native wrapper code, this PR integrates it with LiTr along with exposing it via the demo app. The demo app now provides options to try the native muxer with a normal file transcode, as well as a camera capture. For the camera example, I've also configured the native muxer to generate a single fMP4 which demonstrates something that isn't possible with Android's built in MediaMuxer.
You'll notice that `orientationHint` is not yet used in the new muxer. I plan to add this next, as will require some plumbing/support for file based metadata, rather than stream information.
> Muxers: integrate native muxer with LiTr

- litr/src/main/java/com/linkedin/android/litr/TransformationJob.java
- litr/src/test/java/com/linkedin/android/litr/TransformationJobShould.java
Currently the value of TargetFormat field in the TrackTransformationInfo object is only set in the release method of the TransformationJob class. Also, the value is only set if a corresponding TrackTranscoder object is created successfully. 
Updated logic to always set the value of TargetFormat field in the TrackTransformationInfo object when initiating stats. If the format is not set here initially, then in some scenarios where we fail to create a corresponding TrackTranscoder, the target format value will be reported back as null as part of the MediaTransformationListener callbacks.
> Always set TargetFormat value in TrackTransformationInfo object

- litr/src/main/cpp/audio-processor.cpp
- litr/src/main/java/com/linkedin/android/litr/render/OboeAudioProcessor.kt
I found this issue while implementing a small [resampler](https://github.com/Nailik/AndroidResampler) based on this project.
**Description**
`AudioRenderer`and `AudioOverlayFilter`use:
```
val estimatedTargetSampleCount = ceil(sourceSampleCount * samplingRatio).toInt()
val targetBufferCapacity = estimatedTargetSampleCount * channelCount * BYTES_PER_SAMPLE
```
to calculate the size of the target buffer.
In case this estimation is too small (happens on big differences in samplerate) this results in 2 issues.
**Issue**
`processAudioFrame` in `audio-processor.cpp` doesn't know about the size, resulting in memory access vialoation.
**Fix**
Drop audio when target buffer capacity is reached.
**Issue**
`targetFrame.buffer.limit(targetBufferSize)` throws an `IllegalArgumentException`.
**Fix**
Take …
> Fix potential buffer overflow issue

- litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java
- litr/src/main/java/com/linkedin/android/litr/io/MediaExtractorMediaSource.java
- litr/src/main/java/com/linkedin/android/litr/io/MediaSource.java
- litr/src/main/java/com/linkedin/android/litr/utils/TranscoderUtils.java
- litr/src/test/java/com/linkedin/android/litr/utils/TranscoderUtilsShould.java
1. Fixes a null pointer in TranscoderUtils when retrieving the duration value from a track by checking if the field is present before accessing it.
2. Updated logic of estimateVideoTrackBitrate API in TranscoderUtils to utilize the source media file duration in cases where track specific duration value is null.
3. Updated logic of createTargetMediaFormat API in MediaTransformer class to use a default bit rate of 10_000_000 when we fail to estimate a valid bitrate from the source media track.
4. Added unit tests
> Fixes a null pointer crash (Github Issue #269)

- litr/src/main/java/com/linkedin/android/litr/io/MediaMuxerMediaTarget.java
Release file descriptor even when releasing of android muxer fails with an exception. This is to eliminate any file access issues for client apps.
> Release file descriptor even when releasing of android muxer fails

- litr/src/main/java/com/linkedin/android/litr/TransformationJob.java
- litr/src/main/java/com/linkedin/android/litr/io/MediaMuxerMediaTarget.java
- litr/src/test/java/com/linkedin/android/litr/TransformationJobShould.java
1. Updated release API in TransformationJob such that it only takes care of stopping transcoders and releasing muxers without having to deal with callbacks. Exceptions that can be ignored here are now handled & logged to ensure that the execution continues. 
2. Separated out logic that updates stats (with latest target format) and deletes output files (in error scenarios) into individual methods.
3. Updated overall terminal state (cancelled/completed/failed) handling logic to follow a deterministic order of updating stats, stopping & releasing transcoders, deleting output files, and invoking appropriate callbacks.
Testing Done:
1. Updated unit tests
2. Manual testing to make sure existing functionality did not break and all app callbacks are invoked appropriately
> Refactors TransformationJob to handle terminal states in a more determisitic fashion

- litr-ffmpeg/src/main/cpp/CMakeLists.txt
- litr/src/main/cpp/CMakeLists.txt
Updates CMakeLists.txt to enable 16 KB ELF alignment support for Android 15
> Adds 16KB page size support for Android 15
