linkedin/LiTr

litr-demo/src/main/java/com/linkedin/android/litr/demo/MainActivity.java, litr-filters/build.gradle, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BaseOverlayGlFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BitmapOverlayFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/FrameSequenceAnimationOverlayFilter.java
Overlays (both static and animated) now support rotation. Scale, position and rotation parameters are now passed in more generic constructors.
=> Rotation support in overlays

litr-demo/src/main/java/com/linkedin/android/litr/demo/TranscodeVideoGlFragment.java, litr-filters/build.gradle, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BaseOverlayGlFilter.java
Scaling along Y axis was incorrect for portrait videos, because our sample app scaling computation was incorrect.
=> Fix in portrait y-scaling logic

litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java, litr/src/main/java/com/linkedin/android/litr/MockMediaTransformer.java, litr/src/main/java/com/linkedin/android/litr/test/MockMediaTransformer.java, litr/src/main/java/com/linkedin/android/litr/test/TransformationEvent.java
Introducing MockMediaTransformer, meant to make scenario testing easy. For now, it is just a stub. In the future, it will be able to "play back" user specified listener callbacks.
=> Initial (stub) implementation of MockMediaTransformer

litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoCase.java, litr-demo/src/main/java/com/linkedin/android/litr/demo/MockTranscodeFragment.java, litr-demo/src/main/java/com/linkedin/android/litr/demo/data/MediaTransformationListener.java, litr-demo/src/main/res/layout/fragment_mock_transcode.xml, litr-demo/src/main/res/values/strings.xml, litr/src/main/java/com/linkedin/android/litr/MarshallingTransformationListener.java, litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java, litr/src/main/java/com/linkedin/android/litr/TransformationJob.java, litr/src/test/java/com/linkedin/android/litr/TransformationJobShould.java
Introducing dedicated class to wrap client's TransformationListener and invoke its callbacks on transformation thread or user specified looper thread (including main UI thread)
=> Reworking which thread listener is called back on. 

litr/src/main/java/com/linkedin/android/litr/filter/video/gl/ScaleToFitGlFrameRenderFilter.java, litr/src/main/java/com/linkedin/android/litr/render/GlVideoRenderer.java
Quad setup logic is common and should be performed before applying filters.
=> Move quad setup logic back into GlVideoRenderer

litr/src/main/java/com/linkedin/android/litr/shader/FragmentShaders.java, litr/src/main/java/com/linkedin/android/litr/shader/Shaders.java
As requested, here is the shader to have a black and white filter. Used the same filter as https://github.com/MasayukiSuda/GPUVideo-android/blob/master/gpuv/src/main/java/com/daasuu/gpuv/egl/filter/GlGrayScaleFilter.java
=> add Grayscale shader

NOTICE, litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BrightnessFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BulgeDistortionFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/ContrastFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/CrossHatchFilter.java, litr/src/main/java/com/linkedin/android/litr/filter/video/gl/BaseFrameRenderFilter.java
Bringing in some new filters from https://github.com/MasayukiSuda/Mp4Composer-android project:
- brightness
- contrast
- cross hatch
- bulge
Filters were originally developed by by @MasayukiSuda under MIT License. They were modified to fit LiTr architecture and code style.
=> New frame filters: brightness, contrast, bulge, cross hatch

litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/ExposureFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/GammaFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/HueFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/InversionFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/PosterizationFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/SaturationFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/SepiaFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/VibranceFilter.java
New set of filters that perform simple color manipulation on video frame pixels:
- exposure adjustment
- gamma adjustment
- hue adjustment
- color inversion
- posterization (reduction in color resolution)
- saturation adjustment
- sepia effect
- vibrance adjustment
=> Color manipulation frame filters

litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/GaussianBlurFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/SharpenFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/SphereRefractionFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/SwirlFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/ZoomBlurFilter.java
- Gaussian blur
- sharpen
- sphere refraction
- swirl
- zoom blur
=> Distortion/sharpen frame filters:

litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/Base3x3TextureSamplingFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/ToonFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/WeakPixelInclusionFilter.java
=> 3x3 texture sampling filters:

litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BilateralFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/CgaColorspaceFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/PixelationFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/RgbFilter.java
- bilateral blur
- CGA colorspace
- pixelation
- RGB adjustment
=> New filters:

litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/FalseColorFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/GlassSphereFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/KuwaharaFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/LevelsFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/VignetteFilter.java
- false color
- Kuwahara
- glass sphere
- color levels
- vignette
=> Few filters from gpuimage-android:

litr/src/main/java/com/linkedin/android/litr/filter/video/gl/parameter/Uniform1fv.java, litr/src/main/java/com/linkedin/android/litr/filter/video/gl/parameter/Uniform1iv.java, litr/src/main/java/com/linkedin/android/litr/filter/video/gl/parameter/Uniform2fv.java, litr/src/main/java/com/linkedin/android/litr/filter/video/gl/parameter/Uniform2i.java, litr/src/main/java/com/linkedin/android/litr/filter/video/gl/parameter/Uniform2iv.java, litr/src/main/java/com/linkedin/android/litr/filter/video/gl/parameter/Uniform3i.java, litr/src/main/java/com/linkedin/android/litr/filter/video/gl/parameter/Uniform3iv.java, litr/src/main/java/com/linkedin/android/litr/filter/video/gl/parameter/Uniform4f.java, litr/src/main/java/com/linkedin/android/litr/filter/video/gl/parameter/Uniform4fv.java, litr/src/main/java/com/linkedin/android/litr/filter/video/gl/parameter/Uniform4i.java, litr/src/main/java/com/linkedin/android/litr/filter/video/gl/parameter/Uniform4iv.java, litr/src/main/java/com/linkedin/android/litr/filter/video/gl/parameter/UniformMatrix2fv.java, litr/src/main/java/com/linkedin/android/litr/filter/video/gl/parameter/UniformMatrix3fv.java
Some uniform types were not yet implemented. Adding them here for future use.
=> Add missing uniform shader parameter implementations

litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/ColorBalanceFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/LaplacianFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/ToonFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/WeakPixelInclusionFilter.java, litr/src/main/java/com/linkedin/android/litr/filter/video/gl/shader/VertexShader.java
Since several filters use common 3x3 texture sampling filter, defining it as a common constant
=> New filters: color balance and Laplacian

litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BaseOverlayGlFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/BitmapOverlayFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/FrameSequenceAnimationOverlayFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/SolidBackgroundColorFilter.java, litr/src/main/java/com/linkedin/android/litr/filter/GlFilter.java, litr/src/main/java/com/linkedin/android/litr/filter/video/gl/VideoFrameRenderFilter.java, litr/src/main/java/com/linkedin/android/litr/render/GlRenderUtils.java, litr/src/main/java/com/linkedin/android/litr/render/GlVideoRenderer.java
- introduce release method for GL asset cleanup
- split GL initialization and setting VP matrix
=> Filter improvements:

litr-demo/src/main/java/com/linkedin/android/litr/demo/DemoFilter.java, litr-filters/src/main/java/com/linkedin/android/litr/filter/video/gl/LocalBinaryPatternFilter.java
* Local Binary Pattern (LBP) filter that belongs to a 3x3 sampling filter.
=> A New Filter Added.

litr-demo/src/main/java/com/linkedin/android/litr/demo/VideoWatermarkFragment.java, litr-demo/src/main/java/com/linkedin/android/litr/demo/data/TransformationPresenter.java, litr-demo/src/main/res/layout/fragment_video_watermark.xml, litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java, litr/src/main/java/com/linkedin/android/litr/TransformationOptions.java
Unifying various transformation options/parameters into single Builder class.
=> Unifying transformation options into single class

litr/src/main/java/com/linkedin/android/litr/utils/CodecUtils.java
The current logic of fallback to get codec by type is not working, so I made a fix for it.
=> - Fix the fallbackToGetCodecByType logic

litr/src/main/java/com/linkedin/android/litr/io/MediaExtractorMediaSource.java
- Release unused anymore MediaMetadataRetriever instance
=> Release unused anymore MediaMetadataRetriever instance

litr/src/main/java/com/linkedin/android/litr/MediaTransformer.java, litr/src/main/java/com/linkedin/android/litr/TransformationOptions.java, litr/src/main/java/com/linkedin/android/litr/render/AudioRenderer.kt
We only supported passing in audio filters in `TrackTransform` api. We now support it in simpler api as well.
=> Pass audio filters in TransformationOptions

litr-filters/src/main/java/com/linkedin/android/litr/filter/audio/VolumeFilter.kt, litr/src/main/java/com/linkedin/android/litr/filter/BufferFilter.kt, litr/src/main/java/com/linkedin/android/litr/render/AudioRenderer.kt
Adding a `release` method to `BufferFilter` to release alls its resources when renderer is released.
=> Release BufferFilter's when renderer is released
